### PR TITLE
Add license file to MANIFEST.in

### PR DESCRIPTION
**Pull request by synapticarbors**
It would be helpful to include the license file in the source distribution

### CODE REVIEW

**Comment by omanges** [comment]
@synapticarbors  Really Thank you for your contribution 😊

**Comment by synapticarbors** [comment]
Thanks for the quick review. I'm packaging `turfpy` for conda-forge (https://github.com/conda-forge/staged-recipes/pull/12514) and manually packaged the license file for now. Once you have a new release to pypi that includes the license file in the source distribution, I'll update the recipe. If you have any interest in co-maintaining (https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role) the recipe on conda-forge please let me know. I'm happy to take care of it myself if you rather not.

**Comment by omanges** [comment]
Cool, Yes @sackh and I are interested in co-maintaining the recipe on conda-forge, please also add use both as maintainers 😊

**Comment by synapticarbors** [comment]
@omanges, @sackh -- I've added you both as co-maintainers in the pull request

**Comment by omanges** [comment]
@synapticarbors Just released a new version with your changes for manifest:- https://pypi.org/project/turfpy/

**Pull request merged**
